### ISSUE TITLE
Installation from source fails

### ISSUE THREAD

**Issue by bruno-fs** [dolfinus/setuptools-git-versioning#49]
Installing with pip option `no-binary` results on error.

## How to reproduce
In a virtualenv without setuptools-git-versioning installed, run `pip install --no-binary :all: setuptools-git-versioning`

The error will be something like this

```
  ERROR: Command errored out with exit status 1:
   command: /home/bciconel/SourceCode/setuptools-git-versioning/venv/bin/python /home/bciconel/SourceCode/setuptools-git-versioning/venv/lib64/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpaszqbvaf
       cwd: /tmp/pip-req-build-4qnro2f3
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/home/bciconel/SourceCode/setuptools-git-versioning/venv/lib64/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/bciconel/SourceCode/setuptools-git-versioning/venv/lib64/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/bciconel/SourceCode/setuptools-git-versioning/venv/lib64/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-suhsdn2l/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-suhsdn2l/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-suhsdn2l/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-suhsdn2l/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      from setuptools_git_versioning import version_from_git
    File "/tmp/pip-req-build-4qnro2f3/setuptools_git_versioning.py", line 13, in <module>
      import toml
  ModuleNotFoundError: No module named 'toml'
  ----------------------------------------
  ```

**Comment by bruno-fs** [comment]
In a nutshell, because I don't have them available on the system I need to install this. This system caches required dependencies but not their binaries.

I don't actually run pip like this. It was just a way to reproduce the problem.

**Comment by dolfinus** [comment]
> This system caches required dependencies but not their binaries.

There are no binaries in the current package. `whl` files are successfully cached by pip.

> I don't actually run pip like this

How you've discovered this behavior in the first place?

**Comment by bruno-fs** [comment]
The proxy I ran pip install against don't cache wheels either. only source code.

(If you feel this use case doesn't matter feel free to close the issue, no problem :hugs:)

**Comment by dolfinus** [comment]
I've moved package imports into functions which are using them. This should fix the issue.

I'll notify you about next release

**Comment by dolfinus** [comment]
Please try 1.9.1

**Comment by bruno-fs** [comment]
It now installs, but only in an environment with the requirements previously installed (prior to this version not even this worked)

It still fails on a clean install though, but this is probably due to a lack of a `setup_requires` on `setup.py`.

**Comment by dolfinus** [comment]
Thank you, added `setup_requires` to v1.9.2, please check

**Comment by bruno-fs** [comment]
Awesome! It works. While experimenting with these installations I realized that any version of setuptools<60.9.0 will fail on this installation. But I guess this change is not necessary. People installing from wheel don't have this tight requirement and (I guess?) who's building from source usually will get latest setuptools.

**Comment by bruno-fs** [comment]
To avoid regressions on this I'd consider adding something like this check https://github.com/bruno-fs/setuptools-git-versioning/commit/e029af77054e2fd59030f7e2d2ffe106c7aefc8c

as far as this issue goes, I'd consider it solved anyways :) thanks

**Comment by dolfinus** [comment]
Well, I just removed building and publishing .tag.gz into PyPI

**Comment by dolfinus** [comment]
Returned building sdist back in 1.13.1 due to #72
